<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SearchFieldInput</name>
   <tag></tag>
   <elementGuidId>bc8b8434-22d5-4898-9723-4e8bde2565ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='job-board-kalibrr']/div/kb-job-search/div/div[1]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='job-board-kalibrr']/div/kb-job-search/div/div[1]/div[1]/input</value>
      <webElementGuid>a86909a0-e777-46d3-ab47-3b5cb36e2eb4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
