<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginButton</name>
   <tag></tag>
   <elementGuidId>7c5fdecb-9af8-447b-b91a-014a3ac37998</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/kb-root/kb-login-page/kb-public-view/div/div/div/form/div[2]/div/button[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/kb-root/kb-login-page/kb-public-view/div/div/div/form/div[2]/div/button[1]/div</value>
      <webElementGuid>548adec6-db1c-4116-b58b-296a27b53c64</webElementGuid>
   </webElementProperties>
</WebElementEntity>
